package main

import (
	"context"
	"encoding/json"
	"fmt"
	fdk "github.com/fnproject/fdk-go"
	gp "github.com/oracle/graphpipe-go"
	"io"
	"io/ioutil"
	"net/http"
	"strings"
)

type Imagefile struct {
	Name string `json:"name"`
}

type mymessageAPI struct {
	Id      int
	Message string
}

func main() {
	fdk.Handle(fdk.HandlerFunc(myHandler))
}

func myHandler(ctx context.Context, in io.Reader, out io.Writer) {

	var res [][]float32
	preprocessor := "http://127.0.0.1:4000"
	downloader := "http://127.0.0.1:3000"

	f := &Imagefile{Name: "https://dummy/candy-177355-ja.jpg"}
	json.NewDecoder(in).Decode(f)
	var jpgs []string
	jpgs = append(jpgs, f.Name)


	if !strings.HasPrefix(jpgs[0], "http://") &&
		!strings.HasPrefix(jpgs[0], "https://") {
		// they aren"t http so throw them directly to preprocess
		for j := range jpgs {
			bytes, err := ioutil.ReadFile(jpgs[j])
			if err != nil {
				panic(err)
			}
			jpgs[j] = string(bytes)
		}
		result, err := gp.Remote(preprocessor, jpgs)
		if err != nil {
			fmt.Printf("%+v", err)
			panic(err)
		}
		res = result.([][]float32)
	} else {
		results, err := gp.MultiRemote(http.DefaultClient, downloader,
			preprocessor, []interface{}{jpgs}, nil, nil)
		if err != nil {
			panic(err)
		}
		res = results[0].([][]float32)
	}

        max := make([]float32, len(jpgs))
        arg := make([]int, len(jpgs))
        for i := range res {
                for j := range res[i] {
                        if res[i][j] > max[i] {
                                arg[i] = j
                                max[i] = res[i][j]
                        }
                }
        }

/*	
	for i := range arg {
                //fmt.Printf("image %d is class %d: %s\n", i, arg[i], classes[arg[i]])
                fmt.Printf("image %d is class %d: %s  max= %f \n", i, arg[i], classesjp[arg[i]], max[i])
        }
*/

	max_s := fmt.Sprintf("%.6f", max[0])
	// rmsg := fmt.Sprintf("strSlice[%%#v] -> %#v", res)
	rmsg2 := fmt.Sprintf("{\"id\": 0, \"message\":\"" + "result_class=" + classesjp[arg[0]] + ", probability=" +  max_s + "\"}")

	var m mymessageAPI
	json.Unmarshal([]byte(rmsg2), &m)

	json.NewEncoder(out).Encode(&m)
}

var classes = [...]string{
	"tench, Tinca tinca",
	"goldfish, Carassius auratus",
	"great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias",
	"tiger shark, Galeocerdo cuvieri",
	"hammerhead, hammerhead shark",
	"electric ray, crampfish, numbfish, torpedo",
	"stingray",
	"cock",
	"hen",
	"ostrich, Struthio camelus",
	"brambling, Fringilla montifringilla",
	"goldfinch, Carduelis carduelis",
	"house finch, linnet, Carpodacus mexicanus",
	"junco, snowbird",
	"indigo bunting, indigo finch, indigo bird, Passerina cyanea",
	"robin, American robin, Turdus migratorius",
	"bulbul",
	"jay",
	"magpie",
	"chickadee",
	"water ouzel, dipper",
	"kite",
	"bald eagle, American eagle, Haliaeetus leucocephalus",
	"vulture",
	"great grey owl, great gray owl, Strix nebulosa",
	"European fire salamander, Salamandra salamandra",
	"common newt, Triturus vulgaris",
	"eft",
	"spotted salamander, Ambystoma maculatum",
	"axolotl, mud puppy, Ambystoma mexicanum",
	"bullfrog, Rana catesbeiana",
	"tree frog, tree-frog",
	"tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui",
	"loggerhead, loggerhead turtle, Caretta caretta",
	"leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea",
	"mud turtle",
	"terrapin",
	"box turtle, box tortoise",
	"banded gecko",
	"common iguana, iguana, Iguana iguana",
	"American chameleon, anole, Anolis carolinensis",
	"whiptail, whiptail lizard",
	"agama",
	"frilled lizard, Chlamydosaurus kingi",
	"alligator lizard",
	"Gila monster, Heloderma suspectum",
	"green lizard, Lacerta viridis",
	"African chameleon, Chamaeleo chamaeleon",
	"Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis",
	"African crocodile, Nile crocodile, Crocodylus niloticus",
	"American alligator, Alligator mississipiensis",
	"triceratops",
	"thunder snake, worm snake, Carphophis amoenus",
	"ringneck snake, ring-necked snake, ring snake",
	"hognose snake, puff adder, sand viper",
	"green snake, grass snake",
	"king snake, kingsnake",
	"garter snake, grass snake",
	"water snake",
	"vine snake",
	"night snake, Hypsiglena torquata",
	"boa constrictor, Constrictor constrictor",
	"rock python, rock snake, Python sebae",
	"Indian cobra, Naja naja",
	"green mamba",
	"sea snake",
	"horned viper, cerastes, sand viper, horned asp, Cerastes cornutus",
	"diamondback, diamondback rattlesnake, Crotalus adamanteus",
	"sidewinder, horned rattlesnake, Crotalus cerastes",
	"trilobite",
	"harvestman, daddy longlegs, Phalangium opilio",
	"scorpion",
	"black and gold garden spider, Argiope aurantia",
	"barn spider, Araneus cavaticus",
	"garden spider, Aranea diademata",
	"black widow, Latrodectus mactans",
	"tarantula",
	"wolf spider, hunting spider",
	"tick",
	"centipede",
	"black grouse",
	"ptarmigan",
	"ruffed grouse, partridge, Bonasa umbellus",
	"prairie chicken, prairie grouse, prairie fowl",
	"peacock",
	"quail",
	"partridge",
	"African grey, African gray, Psittacus erithacus",
	"macaw",
	"sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita",
	"lorikeet",
	"coucal",
	"bee eater",
	"hornbill",
	"hummingbird",
	"jacamar",
	"toucan",
	"drake",
	"red-breasted merganser, Mergus serrator",
	"goose",
	"black swan, Cygnus atratus",
	"tusker",
	"echidna, spiny anteater, anteater",
	"platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus",
	"wallaby, brush kangaroo",
	"koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus",
	"wombat",
	"jellyfish",
	"sea anemone, anemone",
	"brain coral",
	"flatworm, platyhelminth",
	"nematode, nematode worm, roundworm",
	"conch",
	"snail",
	"slug",
	"sea slug, nudibranch",
	"chiton, coat-of-mail shell, sea cradle, polyplacophore",
	"chambered nautilus, pearly nautilus, nautilus",
	"Dungeness crab, Cancer magister",
	"rock crab, Cancer irroratus",
	"fiddler crab",
	"king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica",
	"American lobster, Northern lobster, Maine lobster, Homarus americanus",
	"spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish",
	"crayfish, crawfish, crawdad, crawdaddy",
	"hermit crab",
	"isopod",
	"white stork, Ciconia ciconia",
	"black stork, Ciconia nigra",
	"spoonbill",
	"flamingo",
	"little blue heron, Egretta caerulea",
	"American egret, great white heron, Egretta albus",
	"bittern",
	"crane",
	"limpkin, Aramus pictus",
	"European gallinule, Porphyrio porphyrio",
	"American coot, marsh hen, mud hen, water hen, Fulica americana",
	"bustard",
	"ruddy turnstone, Arenaria interpres",
	"red-backed sandpiper, dunlin, Erolia alpina",
	"redshank, Tringa totanus",
	"dowitcher",
	"oystercatcher, oyster catcher",
	"pelican",
	"king penguin, Aptenodytes patagonica",
	"albatross, mollymawk",
	"grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus",
	"killer whale, killer, orca, grampus, sea wolf, Orcinus orca",
	"dugong, Dugong dugon",
	"sea lion",
	"Chihuahua",
	"Japanese spaniel",
	"Maltese dog, Maltese terrier, Maltese",
	"Pekinese, Pekingese, Peke",
	"Shih-Tzu",
	"Blenheim spaniel",
	"papillon",
	"toy terrier",
	"Rhodesian ridgeback",
	"Afghan hound, Afghan",
	"basset, basset hound",
	"beagle",
	"bloodhound, sleuthhound",
	"bluetick",
	"black-and-tan coonhound",
	"Walker hound, Walker foxhound",
	"English foxhound",
	"redbone",
	"borzoi, Russian wolfhound",
	"Irish wolfhound",
	"Italian greyhound",
	"whippet",
	"Ibizan hound, Ibizan Podenco",
	"Norwegian elkhound, elkhound",
	"otterhound, otter hound",
	"Saluki, gazelle hound",
	"Scottish deerhound, deerhound",
	"Weimaraner",
	"Staffordshire bullterrier, Staffordshire bull terrier",
	"American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier",
	"Bedlington terrier",
	"Border terrier",
	"Kerry blue terrier",
	"Irish terrier",
	"Norfolk terrier",
	"Norwich terrier",
	"Yorkshire terrier",
	"wire-haired fox terrier",
	"Lakeland terrier",
	"Sealyham terrier, Sealyham",
	"Airedale, Airedale terrier",
	"cairn, cairn terrier",
	"Australian terrier",
	"Dandie Dinmont, Dandie Dinmont terrier",
	"Boston bull, Boston terrier",
	"miniature schnauzer",
	"giant schnauzer",
	"standard schnauzer",
	"Scotch terrier, Scottish terrier, Scottie",
	"Tibetan terrier, chrysanthemum dog",
	"silky terrier, Sydney silky",
	"soft-coated wheaten terrier",
	"West Highland white terrier",
	"Lhasa, Lhasa apso",
	"flat-coated retriever",
	"curly-coated retriever",
	"golden retriever",
	"Labrador retriever",
	"Chesapeake Bay retriever",
	"German short-haired pointer",
	"vizsla, Hungarian pointer",
	"English setter",
	"Irish setter, red setter",
	"Gordon setter",
	"Brittany spaniel",
	"clumber, clumber spaniel",
	"English springer, English springer spaniel",
	"Welsh springer spaniel",
	"cocker spaniel, English cocker spaniel, cocker",
	"Sussex spaniel",
	"Irish water spaniel",
	"kuvasz",
	"schipperke",
	"groenendael",
	"malinois",
	"briard",
	"kelpie",
	"komondor",
	"Old English sheepdog, bobtail",
	"Shetland sheepdog, Shetland sheep dog, Shetland",
	"collie",
	"Border collie",
	"Bouvier des Flandres, Bouviers des Flandres",
	"Rottweiler",
	"German shepherd, German shepherd dog, German police dog, alsatian",
	"Doberman, Doberman pinscher",
	"miniature pinscher",
	"Greater Swiss Mountain dog",
	"Bernese mountain dog",
	"Appenzeller",
	"EntleBucher",
	"boxer",
	"bull mastiff",
	"Tibetan mastiff",
	"French bulldog",
	"Great Dane",
	"Saint Bernard, St Bernard",
	"Eskimo dog, husky",
	"malamute, malemute, Alaskan malamute",
	"Siberian husky",
	"dalmatian, coach dog, carriage dog",
	"affenpinscher, monkey pinscher, monkey dog",
	"basenji",
	"pug, pug-dog",
	"Leonberg",
	"Newfoundland, Newfoundland dog",
	"Great Pyrenees",
	"Samoyed, Samoyede",
	"Pomeranian",
	"chow, chow chow",
	"keeshond",
	"Brabancon griffon",
	"Pembroke, Pembroke Welsh corgi",
	"Cardigan, Cardigan Welsh corgi",
	"toy poodle",
	"miniature poodle",
	"standard poodle",
	"Mexican hairless",
	"timber wolf, grey wolf, gray wolf, Canis lupus",
	"white wolf, Arctic wolf, Canis lupus tundrarum",
	"red wolf, maned wolf, Canis rufus, Canis niger",
	"coyote, prairie wolf, brush wolf, Canis latrans",
	"dingo, warrigal, warragal, Canis dingo",
	"dhole, Cuon alpinus",
	"African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus",
	"hyena, hyaena",
	"red fox, Vulpes vulpes",
	"kit fox, Vulpes macrotis",
	"Arctic fox, white fox, Alopex lagopus",
	"grey fox, gray fox, Urocyon cinereoargenteus",
	"tabby, tabby cat",
	"tiger cat",
	"Persian cat",
	"Siamese cat, Siamese",
	"Egyptian cat",
	"cougar, puma, catamount, mountain lion, painter, panther, Felis concolor",
	"lynx, catamount",
	"leopard, Panthera pardus",
	"snow leopard, ounce, Panthera uncia",
	"jaguar, panther, Panthera onca, Felis onca",
	"lion, king of beasts, Panthera leo",
	"tiger, Panthera tigris",
	"cheetah, chetah, Acinonyx jubatus",
	"brown bear, bruin, Ursus arctos",
	"American black bear, black bear, Ursus americanus, Euarctos americanus",
	"ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus",
	"sloth bear, Melursus ursinus, Ursus ursinus",
	"mongoose",
	"meerkat, mierkat",
	"tiger beetle",
	"ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle",
	"ground beetle, carabid beetle",
	"long-horned beetle, longicorn, longicorn beetle",
	"leaf beetle, chrysomelid",
	"dung beetle",
	"rhinoceros beetle",
	"weevil",
	"fly",
	"bee",
	"ant, emmet, pismire",
	"grasshopper, hopper",
	"cricket",
	"walking stick, walkingstick, stick insect",
	"cockroach, roach",
	"mantis, mantid",
	"cicada, cicala",
	"leafhopper",
	"lacewing, lacewing fly",
	"dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk",
	"damselfly",
	"admiral",
	"ringlet, ringlet butterfly",
	"monarch, monarch butterfly, milkweed butterfly, Danaus plexippus",
	"cabbage butterfly",
	"sulphur butterfly, sulfur butterfly",
	"lycaenid, lycaenid butterfly",
	"starfish, sea star",
	"sea urchin",
	"sea cucumber, holothurian",
	"wood rabbit, cottontail, cottontail rabbit",
	"hare",
	"Angora, Angora rabbit",
	"hamster",
	"porcupine, hedgehog",
	"fox squirrel, eastern fox squirrel, Sciurus niger",
	"marmot",
	"beaver",
	"guinea pig, Cavia cobaya",
	"sorrel",
	"zebra",
	"hog, pig, grunter, squealer, Sus scrofa",
	"wild boar, boar, Sus scrofa",
	"warthog",
	"hippopotamus, hippo, river horse, Hippopotamus amphibius",
	"ox",
	"water buffalo, water ox, Asiatic buffalo, Bubalus bubalis",
	"bison",
	"ram, tup",
	"bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis",
	"ibex, Capra ibex",
	"hartebeest",
	"impala, Aepyceros melampus",
	"gazelle",
	"Arabian camel, dromedary, Camelus dromedarius",
	"llama",
	"weasel",
	"mink",
	"polecat, fitch, foulmart, foumart, Mustela putorius",
	"black-footed ferret, ferret, Mustela nigripes",
	"otter",
	"skunk, polecat, wood pussy",
	"badger",
	"armadillo",
	"three-toed sloth, ai, Bradypus tridactylus",
	"orangutan, orang, orangutang, Pongo pygmaeus",
	"gorilla, Gorilla gorilla",
	"chimpanzee, chimp, Pan troglodytes",
	"gibbon, Hylobates lar",
	"siamang, Hylobates syndactylus, Symphalangus syndactylus",
	"guenon, guenon monkey",
	"patas, hussar monkey, Erythrocebus patas",
	"baboon",
	"macaque",
	"langur",
	"colobus, colobus monkey",
	"proboscis monkey, Nasalis larvatus",
	"marmoset",
	"capuchin, ringtail, Cebus capucinus",
	"howler monkey, howler",
	"titi, titi monkey",
	"spider monkey, Ateles geoffroyi",
	"squirrel monkey, Saimiri sciureus",
	"Madagascar cat, ring-tailed lemur, Lemur catta",
	"indri, indris, Indri indri, Indri brevicaudatus",
	"Indian elephant, Elephas maximus",
	"African elephant, Loxodonta africana",
	"lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens",
	"giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca",
	"barracouta, snoek",
	"eel",
	"coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch",
	"rock beauty, Holocanthus tricolor",
	"anemone fish",
	"sturgeon",
	"gar, garfish, garpike, billfish, Lepisosteus osseus",
	"lionfish",
	"puffer, pufferfish, blowfish, globefish",
	"abacus",
	"abaya",
	"academic gown, academic robe, judge's robe",
	"accordion, piano accordion, squeeze box",
	"acoustic guitar",
	"aircraft carrier, carrier, flattop, attack aircraft carrier",
	"airliner",
	"airship, dirigible",
	"altar",
	"ambulance",
	"amphibian, amphibious vehicle",
	"analog clock",
	"apiary, bee house",
	"apron",
	"ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin",
	"assault rifle, assault gun",
	"backpack, back pack, knapsack, packsack, rucksack, haversack",
	"bakery, bakeshop, bakehouse",
	"balance beam, beam",
	"balloon",
	"ballpoint, ballpoint pen, ballpen, Biro",
	"Band Aid",
	"banjo",
	"bannister, banister, balustrade, balusters, handrail",
	"barbell",
	"barber chair",
	"barbershop",
	"barn",
	"barometer",
	"barrel, cask",
	"barrow, garden cart, lawn cart, wheelbarrow",
	"baseball",
	"basketball",
	"bassinet",
	"bassoon",
	"bathing cap, swimming cap",
	"bath towel",
	"bathtub, bathing tub, bath, tub",
	"beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon",
	"beacon, lighthouse, beacon light, pharos",
	"beaker",
	"bearskin, busby, shako",
	"beer bottle",
	"beer glass",
	"bell cote, bell cot",
	"bib",
	"bicycle-built-for-two, tandem bicycle, tandem",
	"bikini, two-piece",
	"binder, ring-binder",
	"binoculars, field glasses, opera glasses",
	"birdhouse",
	"boathouse",
	"bobsled, bobsleigh, bob",
	"bolo tie, bolo, bola tie, bola",
	"bonnet, poke bonnet",
	"bookcase",
	"bookshop, bookstore, bookstall",
	"bottlecap",
	"bow",
	"bow tie, bow-tie, bowtie",
	"brass, memorial tablet, plaque",
	"brassiere, bra, bandeau",
	"breakwater, groin, groyne, mole, bulwark, seawall, jetty",
	"breastplate, aegis, egis",
	"broom",
	"bucket, pail",
	"buckle",
	"bulletproof vest",
	"bullet train, bullet",
	"butcher shop, meat market",
	"cab, hack, taxi, taxicab",
	"caldron, cauldron",
	"candle, taper, wax light",
	"cannon",
	"canoe",
	"can opener, tin opener",
	"cardigan",
	"car mirror",
	"carousel, carrousel, merry-go-round, roundabout, whirligig",
	"carpenter's kit, tool kit",
	"carton",
	"car wheel",
	"cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
	"cassette",
	"cassette player",
	"castle",
	"catamaran",
	"CD player",
	"cello, violoncello",
	"cellular telephone, cellular phone, cellphone, cell, mobile phone",
	"chain",
	"chainlink fence",
	"chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour",
	"chain saw, chainsaw",
	"chest",
	"chiffonier, commode",
	"chime, bell, gong",
	"china cabinet, china closet",
	"Christmas stocking",
	"church, church building",
	"cinema, movie theater, movie theatre, movie house, picture palace",
	"cleaver, meat cleaver, chopper",
	"cliff dwelling",
	"cloak",
	"clog, geta, patten, sabot",
	"cocktail shaker",
	"coffee mug",
	"coffeepot",
	"coil, spiral, volute, whorl, helix",
	"combination lock",
	"computer keyboard, keypad",
	"confectionery, confectionary, candy store",
	"container ship, containership, container vessel",
	"convertible",
	"corkscrew, bottle screw",
	"cornet, horn, trumpet, trump",
	"cowboy boot",
	"cowboy hat, ten-gallon hat",
	"cradle",
	"crane",
	"crash helmet",
	"crate",
	"crib, cot",
	"Crock Pot",
	"croquet ball",
	"crutch",
	"cuirass",
	"dam, dike, dyke",
	"desk",
	"desktop computer",
	"dial telephone, dial phone",
	"diaper, nappy, napkin",
	"digital clock",
	"digital watch",
	"dining table, board",
	"dishrag, dishcloth",
	"dishwasher, dish washer, dishwashing machine",
	"disk brake, disc brake",
	"dock, dockage, docking facility",
	"dogsled, dog sled, dog sleigh",
	"dome",
	"doormat, welcome mat",
	"drilling platform, offshore rig",
	"drum, membranophone, tympan",
	"drumstick",
	"dumbbell",
	"Dutch oven",
	"electric fan, blower",
	"electric guitar",
	"electric locomotive",
	"entertainment center",
	"envelope",
	"espresso maker",
	"face powder",
	"feather boa, boa",
	"file, file cabinet, filing cabinet",
	"fireboat",
	"fire engine, fire truck",
	"fire screen, fireguard",
	"flagpole, flagstaff",
	"flute, transverse flute",
	"folding chair",
	"football helmet",
	"forklift",
	"fountain",
	"fountain pen",
	"four-poster",
	"freight car",
	"French horn, horn",
	"frying pan, frypan, skillet",
	"fur coat",
	"garbage truck, dustcart",
	"gasmask, respirator, gas helmet",
	"gas pump, gasoline pump, petrol pump, island dispenser",
	"goblet",
	"go-kart",
	"golf ball",
	"golfcart, golf cart",
	"gondola",
	"gong, tam-tam",
	"gown",
	"grand piano, grand",
	"greenhouse, nursery, glasshouse",
	"grille, radiator grille",
	"grocery store, grocery, food market, market",
	"guillotine",
	"hair slide",
	"hair spray",
	"half track",
	"hammer",
	"hamper",
	"hand blower, blow dryer, blow drier, hair dryer, hair drier",
	"hand-held computer, hand-held microcomputer",
	"handkerchief, hankie, hanky, hankey",
	"hard disc, hard disk, fixed disk",
	"harmonica, mouth organ, harp, mouth harp",
	"harp",
	"harvester, reaper",
	"hatchet",
	"holster",
	"home theater, home theatre",
	"honeycomb",
	"hook, claw",
	"hoopskirt, crinoline",
	"horizontal bar, high bar",
	"horse cart, horse-cart",
	"hourglass",
	"iPod",
	"iron, smoothing iron",
	"jack-o'-lantern",
	"jean, blue jean, denim",
	"jeep, landrover",
	"jersey, T-shirt, tee shirt",
	"jigsaw puzzle",
	"jinrikisha, ricksha, rickshaw",
	"joystick",
	"kimono",
	"knee pad",
	"knot",
	"lab coat, laboratory coat",
	"ladle",
	"lampshade, lamp shade",
	"laptop, laptop computer",
	"lawn mower, mower",
	"lens cap, lens cover",
	"letter opener, paper knife, paperknife",
	"library",
	"lifeboat",
	"lighter, light, igniter, ignitor",
	"limousine, limo",
	"liner, ocean liner",
	"lipstick, lip rouge",
	"Loafer",
	"lotion",
	"loudspeaker, speaker, speaker unit, loudspeaker system, speaker system",
	"loupe, jeweler's loupe",
	"lumbermill, sawmill",
	"magnetic compass",
	"mailbag, postbag",
	"mailbox, letter box",
	"maillot",
	"maillot, tank suit",
	"manhole cover",
	"maraca",
	"marimba, xylophone",
	"mask",
	"matchstick",
	"maypole",
	"maze, labyrinth",
	"measuring cup",
	"medicine chest, medicine cabinet",
	"megalith, megalithic structure",
	"microphone, mike",
	"microwave, microwave oven",
	"military uniform",
	"milk can",
	"minibus",
	"miniskirt, mini",
	"minivan",
	"missile",
	"mitten",
	"mixing bowl",
	"mobile home, manufactured home",
	"Model T",
	"modem",
	"monastery",
	"monitor",
	"moped",
	"mortar",
	"mortarboard",
	"mosque",
	"mosquito net",
	"motor scooter, scooter",
	"mountain bike, all-terrain bike, off-roader",
	"mountain tent",
	"mouse, computer mouse",
	"mousetrap",
	"moving van",
	"muzzle",
	"nail",
	"neck brace",
	"necklace",
	"nipple",
	"notebook, notebook computer",
	"obelisk",
	"oboe, hautboy, hautbois",
	"ocarina, sweet potato",
	"odometer, hodometer, mileometer, milometer",
	"oil filter",
	"organ, pipe organ",
	"oscilloscope, scope, cathode-ray oscilloscope, CRO",
	"overskirt",
	"oxcart",
	"oxygen mask",
	"packet",
	"paddle, boat paddle",
	"paddlewheel, paddle wheel",
	"padlock",
	"paintbrush",
	"pajama, pyjama, pj's, jammies",
	"palace",
	"panpipe, pandean pipe, syrinx",
	"paper towel",
	"parachute, chute",
	"parallel bars, bars",
	"park bench",
	"parking meter",
	"passenger car, coach, carriage",
	"patio, terrace",
	"pay-phone, pay-station",
	"pedestal, plinth, footstall",
	"pencil box, pencil case",
	"pencil sharpener",
	"perfume, essence",
	"Petri dish",
	"photocopier",
	"pick, plectrum, plectron",
	"pickelhaube",
	"picket fence, paling",
	"pickup, pickup truck",
	"pier",
	"piggy bank, penny bank",
	"pill bottle",
	"pillow",
	"ping-pong ball",
	"pinwheel",
	"pirate, pirate ship",
	"pitcher, ewer",
	"plane, carpenter's plane, woodworking plane",
	"planetarium",
	"plastic bag",
	"plate rack",
	"plow, plough",
	"plunger, plumber's helper",
	"Polaroid camera, Polaroid Land camera",
	"pole",
	"police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria",
	"poncho",
	"pool table, billiard table, snooker table",
	"pop bottle, soda bottle",
	"pot, flowerpot",
	"potter's wheel",
	"power drill",
	"prayer rug, prayer mat",
	"printer",
	"prison, prison house",
	"projectile, missile",
	"projector",
	"puck, hockey puck",
	"punching bag, punch bag, punching ball, punchball",
	"purse",
	"quill, quill pen",
	"quilt, comforter, comfort, puff",
	"racer, race car, racing car",
	"racket, racquet",
	"radiator",
	"radio, wireless",
	"radio telescope, radio reflector",
	"rain barrel",
	"recreational vehicle, RV, R.V.",
	"reel",
	"reflex camera",
	"refrigerator, icebox",
	"remote control, remote",
	"restaurant, eating house, eating place, eatery",
	"revolver, six-gun, six-shooter",
	"rifle",
	"rocking chair, rocker",
	"rotisserie",
	"rubber eraser, rubber, pencil eraser",
	"rugby ball",
	"rule, ruler",
	"running shoe",
	"safe",
	"safety pin",
	"saltshaker, salt shaker",
	"sandal",
	"sarong",
	"sax, saxophone",
	"scabbard",
	"scale, weighing machine",
	"school bus",
	"schooner",
	"scoreboard",
	"screen, CRT screen",
	"screw",
	"screwdriver",
	"seat belt, seatbelt",
	"sewing machine",
	"shield, buckler",
	"shoe shop, shoe-shop, shoe store",
	"shoji",
	"shopping basket",
	"shopping cart",
	"shovel",
	"shower cap",
	"shower curtain",
	"ski",
	"ski mask",
	"sleeping bag",
	"slide rule, slipstick",
	"sliding door",
	"slot, one-armed bandit",
	"snorkel",
	"snowmobile",
	"snowplow, snowplough",
	"soap dispenser",
	"soccer ball",
	"sock",
	"solar dish, solar collector, solar furnace",
	"sombrero",
	"soup bowl",
	"space bar",
	"space heater",
	"space shuttle",
	"spatula",
	"speedboat",
	"spider web, spider's web",
	"spindle",
	"sports car, sport car",
	"spotlight, spot",
	"stage",
	"steam locomotive",
	"steel arch bridge",
	"steel drum",
	"stethoscope",
	"stole",
	"stone wall",
	"stopwatch, stop watch",
	"stove",
	"strainer",
	"streetcar, tram, tramcar, trolley, trolley car",
	"stretcher",
	"studio couch, day bed",
	"stupa, tope",
	"submarine, pigboat, sub, U-boat",
	"suit, suit of clothes",
	"sundial",
	"sunglass",
	"sunglasses, dark glasses, shades",
	"sunscreen, sunblock, sun blocker",
	"suspension bridge",
	"swab, swob, mop",
	"sweatshirt",
	"swimming trunks, bathing trunks",
	"swing",
	"switch, electric switch, electrical switch",
	"syringe",
	"table lamp",
	"tank, army tank, armored combat vehicle, armoured combat vehicle",
	"tape player",
	"teapot",
	"teddy, teddy bear",
	"television, television system",
	"tennis ball",
	"thatch, thatched roof",
	"theater curtain, theatre curtain",
	"thimble",
	"thresher, thrasher, threshing machine",
	"throne",
	"tile roof",
	"toaster",
	"tobacco shop, tobacconist shop, tobacconist",
	"toilet seat",
	"torch",
	"totem pole",
	"tow truck, tow car, wrecker",
	"toyshop",
	"tractor",
	"trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi",
	"tray",
	"trench coat",
	"tricycle, trike, velocipede",
	"trimaran",
	"tripod",
	"triumphal arch",
	"trolleybus, trolley coach, trackless trolley",
	"trombone",
	"tub, vat",
	"turnstile",
	"typewriter keyboard",
	"umbrella",
	"unicycle, monocycle",
	"upright, upright piano",
	"vacuum, vacuum cleaner",
	"vase",
	"vault",
	"velvet",
	"vending machine",
	"vestment",
	"viaduct",
	"violin, fiddle",
	"volleyball",
	"waffle iron",
	"wall clock",
	"wallet, billfold, notecase, pocketbook",
	"wardrobe, closet, press",
	"warplane, military plane",
	"washbasin, handbasin, washbowl, lavabo, wash-hand basin",
	"washer, automatic washer, washing machine",
	"water bottle",
	"water jug",
	"water tower",
	"whiskey jug",
	"whistle",
	"wig",
	"window screen",
	"window shade",
	"Windsor tie",
	"wine bottle",
	"wing",
	"wok",
	"wooden spoon",
	"wool, woolen, woollen",
	"worm fence, snake fence, snake-rail fence, Virginia fence",
	"wreck",
	"yawl",
	"yurt",
	"web site, website, internet site, site",
	"comic book",
	"crossword puzzle, crossword",
	"street sign",
	"traffic light, traffic signal, stoplight",
	"book jacket, dust cover, dust jacket, dust wrapper",
	"menu",
	"plate",
	"guacamole",
	"consomme",
	"hot pot, hotpot",
	"trifle",
	"ice cream, icecream",
	"ice lolly, lolly, lollipop, popsicle",
	"French loaf",
	"bagel, beigel",
	"pretzel",
	"cheeseburger",
	"hotdog, hot dog, red hot",
	"mashed potato",
	"head cabbage",
	"broccoli",
	"cauliflower",
	"zucchini, courgette",
	"spaghetti squash",
	"acorn squash",
	"butternut squash",
	"cucumber, cuke",
	"artichoke, globe artichoke",
	"bell pepper",
	"cardoon",
	"mushroom",
	"Granny Smith",
	"strawberry",
	"orange",
	"lemon",
	"fig",
	"pineapple, ananas",
	"banana",
	"jackfruit, jak, jack",
	"custard apple",
	"pomegranate",
	"hay",
	"carbonara",
	"chocolate sauce, chocolate syrup",
	"dough",
	"meat loaf, meatloaf",
	"pizza, pizza pie",
	"potpie",
	"burrito",
	"red wine",
	"espresso",
	"cup",
	"eggnog",
	"alp",
	"bubble",
	"cliff, drop, drop-off",
	"coral reef",
	"geyser",
	"lakeside, lakeshore",
	"promontory, headland, head, foreland",
	"sandbar, sand bar",
	"seashore, coast, seacoast, sea-coast",
	"valley, vale",
	"volcano",
	"ballplayer, baseball player",
	"groom, bridegroom",
	"scuba diver",
	"rapeseed",
	"daisy",
	"yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum",
	"corn",
	"acorn",
	"hip, rose hip, rosehip",
	"buckeye, horse chestnut, conker",
	"coral fungus",
	"agaric",
	"gyromitra",
	"stinkhorn, carrion fungus",
	"earthstar",
	"hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa",
	"bolete",
	"ear, spike, capitulum",
	"toilet tissue, toilet paper, bathroom tissue",
}

// These Japanese words are based on machine translation and not fully examined. They might not be accurate.
var classesjp = [...]string{
"テンチ、ティンカティンカ",
"金魚、Carassius auratus",
"ホオジロザメ、ホオジロザメ、人食い、人食い鮫、Carcharodon carcharias",
"タイガーシャーク、Galeocerdo cuvieri",
"シュモクザメ、シュモクザメ",
"電灯・イカ・ナマズ・魚雷",
"アカエイ",
"コック",
"変",
"ダチョウ、Struthioのラクダ",
"括弧書き、Fringilla montifringilla",
"goldfinch、Carduelis carduelis",
"家のフィンチ、linnet、Carpodacus mexicanus",
"ユンコ、スノーバード",
"インディゴホオジロ、インディゴフィンチ、インディゴバード、Passerina cyanea",
"ロビン、アメリカンロビン、Turdus migratorius",
"泡",
"ジェイ",
"カササギ",
"チカディー",
"ウォーターオゼル、ディッパー",
"凧",
"白頭ワシ、アメリカワシ、Haliaeetus leucocephalus",
"ハゲタカ",
"ホオジロフクロウ、ホオジロフクロウ、Strix nebulosa",
"ヨーロッパの火のサンショウウオ、Salamandra salamandra",
"一般的なイモリ、Triturus vulgaris",
"あります",
"斑点を付けられたサンショウウオ、Ambystoma maculatum",
"axolotl、泥の子犬、Ambystoma mexicanum",
"ウシガエル、ラナcatesbeiana",
"木のカエル、木のカエル",
"尾のカエル、ベルヒキガエル、リブ付きヒキガエル、尾ヒキガエル、Ascaphus trui",
"アカウミガメ、アカウミガメ、カレッタカレッタ",
"オサガメ、オサガメ、オサガメ、Dermochelys coriacea",
"泥タートル",
"テラピン",
"ボックスカメ、ボックスカメ",
"縞ヤモリ",
"一般的なイグアナ、イグアナ、イグアナイグアナ",
"アメリカンカメレオン、アノール、Anolis carolinensis",
"ホイップテイル、ホイップテイルトカゲ",
"宗教",
"焼きトカゲ、Chlamydosaurus kingii",
"ワニトカゲ",
"アメリカドクトカゲ、Heloderma",
"緑のトカゲ、Lacerta viridis",
"アフリカカメレオン、Chamaeleo chamaeleon",
"コモドドラゴン、コモドトカゲ、ドラゴントカゲ、巨大トカゲ、Varanus komodoensis",
"アフリカのワニ、ナイルワニ、Crocodylus niloticus",
"アメリカのワニ、ワニのmississippiensis",
"トリケラトプス",
"サンダースネーク、ワームスネーク、Carphophis amoenus",
"リングネックスネーク、リングネックスネーク、リングスネーク",
"コガネムシヘビ、パフアダー、サンドバイパー",
"緑のヘビ、草のヘビ",
"キングスネーク、キングスネーク",
"ガーターヘビ、草ヘビ",
"水蛇",
"つる蛇",
"夜のヘビ、Hypsiglena torquata",
"ボアコンストリクター、コンストリクターコンストラクター",
"ロックパイソン、ロックスネーク、パイソンsebae",
"インドのコブラ、よく、よく",
"グリーンマンバ",
"海蛇",
"角のある毒蛇、cerastes、砂の毒蛇、角のあるasp、Cerastes cornutus",
"コナガガラガラヘビ、Crotalus adamanteus",
"サイドワインダー、角のあるガラガラヘビ、Crotalusのセラステ",
"三葉虫",
"ハーベストマン、パパ・ロングレッグス",
"サソリ",
"黒と金の庭のクモ、Argiope aurantia",
"納屋クモ、Araneus cavaticus",
"庭のクモ、クモ冠;",
"黒い未亡人、Latrodectus mactans",
"タランチュラ",
"オオカミグモ、狩猟クモ",
"ダニ",
"ムカデ",
"黒ライチョウ",
"プルミガン",
"ライチョウ、ヤマウズラ、Bonasa umbellus",
"大草原の鶏、大草原のライチョウ、大草原の鶏",
"孔雀",
"ウズラ",
"ヤマウズラ",
"アフリカ灰色、アフリカ灰色、Psittacus erithacus",
"コンゴウインコ",
"硫黄の紋付きオウム、Katatoe galerita、Cacatua galerita",
"ロリキート",
"クーカル",
"ミツバチ",
"サイチョウ",
"ハチドリ",
"ジャカマー",
"オオハシ",
"ドレイク",
"レッドブレストマーガンサー、マーガスセーター",
"ガチョウ",
"黒い白鳥、白鳥座atratus",
"タスカー",
"エキドナ",
"カモノハシ、カモノハシ、カモノハシ、カモノハシ",
"ワラビー、ブラシカンガルー",
"コアラ、コアラ、カンガルーベア、先住民クマ",
"ウォンバット",
"クラゲ",
"イソギンチャク、アネモネ",
"脳サンゴ",
"平虫、platyhelminth",
"線虫、線虫、回虫",
"巻き貝",
"かたつむり",
"ナメクジ",
"ウミウシ、ウミウシ",
"キトン、紋章入りシェル、海の揺りかご、polyplacophora",
"オウムガイの実",
"ダンジネスカニ、ガンマジスター",
"カニ、がん虹彩",
"フィドラーカニ",
"アラスカのカニ、アラスカのカニ、アラスカのカニ、Paralithodes camtschatica",
"アメリカのロブスター、ノーザンロブスター、メインのロブスター、Homarus americanus",
"とげのあるロブスター、lan??gouste、ロックロブスター、ザリガニ、ザリガニ、海の ザリガニ",
"ザリガニ、ザリガニ、ザリガニ、ザリガニ",
"ヤドカリ",
"等脚",
"コウノトリ、チコニア",
"クロコウノトリ、チコニアニグラ",
"スプーンビル",
"フラミンゴ",
"アオサギ、Egretta caerulea",
"アメリカの白鷺、オオアオサギ、Egretta albus",
"にがり",
"クレーン",
"リンプキン、アラマスの画像",
"ヨーロッパgallinule、ガスリー",
"アメリカのオオバン、湿地編、泥編、水鶏、フリカ・アメリカーナ",
"バスタード",
"キョウジョシギ、Arenariaトランスレータ",
"赤バックサンドパイパー、ダンリン、エロリアアルピナ",
"redshank、Tringa totanus",
"ドウィッチャー",
"オイスターキャッチャー、オイスターキャッチャー",
"ペリカン",
"キングペンギン、Aptenodytes patagonica",
"アホウドリ、mollymawk",
"コククジラ、コククジラ、デビルフィッシュ、Eschrichtius gibbosus、Eschrichtius robustus",
"シャチ、シャチ、シャチ、グランパス、ウルフ、シャチシャチ",
"ジュゴン、ジュゴンジュゴン",
"アシカ",
"チワワ",
"狆",
"マルタ犬、マルタテリア、マルタ",
"ペキニーズ、ペキニーズ、ペイク",
"シーズー",
"ブレナムスパニエル",
"蝶",
"トイテリア",
"ローデシアン・リッジバック",
"アフガンハウンド、アフガン",
"バセット、バセットハウンド",
"ビーグル",
"ブラッドハウンド、スルーハウンド",
"ブルーティック",
"黒褐色のクーンハウンド",
"ウォーカーハウンド、ウォーカーフォックスハウンド",
"イングリッシュフォックスハウンド",
"レッドボーン",
"ボルゾイ、ロシアのウルフハウンド",
"アイルランドのウルフハウンド",
"イタリアのグレイハウンド",
"ウィペット",
"イビザンハウンド、イビザンポデンコ",
"ノルウェーのエルクハウンド、エルクハウンド",
"カワウソ、カワウソ",
"サルキ、ガゼルハウンド",
"スコットランドディアハウンド、ディアハウンド",
"ワイマラナー",
"スタッフォードシャー・ブルテリア、スタッフォードシャー・ブルテリア",
"アメリカンスタッフォードシャーテリア、スタッフォードシャーテリア、アメリカンピットブルテリア、ピットブルテリア",
"ベドリントンテリア",
"ボーダーテリア",
"ケリーブルーテリア",
"アイルランドのテリア",
"ノーフォークテリア",
"ノーリッチテリア",
"ヨークシャーテリア",
"ワイヤーヘアフォックステリア",
"レイクランドテリア",
"Sealyhamテリア、Sealyham",
"エアデール、エアデールテリア",
"ケアン、ケアンテリア",
"オーストラリアのテリア",
"Dandie Dinmont、Dandie Dinmontテリア",
"ボストンブル、ボストンテリア",
"ミニチュアシュナウザー",
"巨大シュナウザー",
"標準シュナウザー",
"スコッチテリア、スコティッシュテリア、スコッティ",
"チベットテリア、菊犬",
"シルキーテリア、シドニーシルキー",
"ソフトコーテッドウィートテリア",
"ウェストハイランドホワイトテリア",
"ラサ、ラサ・アプソ",
"フラットコート・レトリーバー",
"カーリーコートレトリーバー",
"ゴールデンレトリバー",
"ラブラドールレトリーバー",
"チェサピークベイレトリーバー",
"ドイツの短髪ポインター",
"チェッカー、ハンガリーのポインタ",
"英語セット",
"アイリッシュセッター、レッドセッター",
"ゴードンセット",
"ブルターニュスパニエル",
"クランバー、クランバースパニエル",
"イングリッシュスプリンガー、イングリッシュスプリンガースパニエル",
"ウェールズのスプリンガースパニエル",
"コッカースパニエル、英語コッカースパニエル、コッカー",
"サセックススパニエル",
"アイルランドの水スパニエル",
"犬",
"スキッパーキ",
"Groenendael",
"マリノア",
"ブリアード",
"ケルピー",
"コモンドール",
"オールドイングリッシュシープドッグ",
"シェトランドシープドッグ、シェトランドシープドッグ",
"コリー",
"ボーダーコリー",
"ブビエデフランドル、ブビエデフランドル",
"ロットワイラー",
"ジャーマン・シェパード、ジャーマン・シェパード犬、ドイツの警察犬、アルザス",
"ドーベルマン、ドーベルマンピンサー",
"ミニチュアピンシャー",
"大きいスイス山犬",
"バーニーズマウンテンドッグ",
"アッペンツェル",
"EntleBucher",
"ボクサー",
"ブルマスティフ",
"チベタン・マスティフ",
"フレンチ・ブルドッグ",
"グレートデーン",
"セントバーナード、セントバーナード",
"エスキモー犬、ハスキー",
"アラスカマラミュート",
"シベリアンハスキー",
"ダルメシアン、コーチ犬、馬車犬",
"affenpinscher、サルピンシャー、サル犬",
"バセンジー",
"パグ、パグ犬",
"レオンバーグ",
"ニューファンドランド、ニューファンドランド犬",
"グレートピレネー",
"サモエド、サモエデ",
"ポメラニアン",
"チャウチャウ",
"キーホンド",
"ブラバンコングリフォン",
"ペンブローク、ペンブロークウェールズコーギー",
"カーディガン、カーディガンウェールズコーギー",
"トイプードル",
"ミニチュアプードル",
"標準プードル",
"メキシコの無毛",
"材木オオカミ、灰色オオカミ、灰色オオカミ、Canis lupus",
"ホワイトオオカミ、ホッキョクオオカミ、Canis lupus tundrarum",
"赤いオオカミ、オオカミ、Canis rufus、Canis niger",
"コヨーテ、大草原のオオカミ、ブラシオオカミ、Canis latrans",
"ディンゴ、warrigal、ワラガル、Canis dingo",
"滴、カナ・アルピナス",
"アフリカの狩猟犬、ハイエナ犬、ケープ狩猟犬、Lycaon pictus",
"ハイエナ、ハイエナ",
"キツネ、Vulpes vulpes",
"キツネ、Vulpes macrotis",
"ホッキョクギツネ、ホワイトキツネ、Alopex lagopus",
"灰色キツネ、灰色キツネ、Urocyon cinereoargenteus",
"ぶち、ぶち猫",
"虎猫",
"ペルシャ猫",
"シャム猫、シャム",
"エジプト猫",
"クーガー、プーマ、カタマウント、マウンテンライオン、画家、豹、Felis concolor",
"リンクス、カタマウント",
"ヒョウ、ヒョウ",
"ユキヒョウ、オンス、Panthera uncia",
"ジャガー、パンサー、Panthera onca、Felis onca",
"ライオン、百獣の王、パンテーラレオ",
"タイガー、パンテーラチグリス",
"チーター、チーター、Acinonyx jubatus",
"ヒグマ、ブルーイン、Ursus arctos",
"アメリカのツキノワグマ、ツキノワグマ、Ursus americanus、Euarctos America",
"アイスベア、ホッキョクグマ、Ursus Maritimus、Thalarctos maritimus",
"ナマケモノ、Melursus ursinus、Ursus ursinus",
"マングース",
"ミーアキャット、スケール",
"タイガービートル",
"てんとう虫、てんとう虫、てんとう虫、てんとう虫、てんとう虫",
"オサムシ、オサムシ",
"カミキリムシ、ロングコーン、カミキリムシ",
"ハムシ、ハムシ科",
"カブトムシの内容",
"カブトムシ",
"ゾウムシ",
"飛ぶ",
"蜂",
"アリ、エメット、ピズミール",
"バッタ、ホッパー",
"クリケット",
"ステッキ、ステッキ、虫",
"ゴキブリ、ゴキブリ",
"カマキリ、mantid",
"蝉、蝉",
"ハタバタ",
"クサカゲロウ、クサカゲロウ",
"トンボ、かがり針、悪魔のかが り針、ミシン針、ヘビの送り装置、ヘビの医者、蚊のタカ、スキーターのタカ",
"わがままに",
"提督",
"リングレット、リングレットバタフライ",
"モナーク、モナークバタフライ、トウワタ蝶、Danaus plexippus",
"キャベツ蝶",
"硫黄蝶、硫黄蝶",
"ライカニード",
"ヒトデ、海の星",
"うに",
"ナマコ、holothurian",
"木うさぎ",
"晴れ",
"アンゴラ、アンゴラウサギ",
"ハムスター",
"ヤマアラシ、ハリネズミ",
"キツネリス、東キツネリス、Sciurus niger",
"マーモット",
"ビーバー",
"モルモット、モルモット",
"栗色",
"シマウマ",
"豚、豚、挽く人、きしむ、Sus scrofa",
"イノシシ、イノシシ、Sus scrofa",
"イボイノシシ",
"カバ、カバ、川馬、カバ、両生類",
"牛",
"水牛、水牛、アジアバッファロー、Bubalus bubalis",
"バイソン",
"ラム、タップ",
"ビッグホーン、ビッグホーン羊、シマロン、ロッキーマウン テンビッグホーン、ロッキーマウンテン羊、オービスカナデンシス",
"アイベックス、カプラアイベックス",
"ハーテビースト",
"インパラ、Aepyceros melampus",
"ガゼル",
"アラビアラクダ、ヒトコブラクダ、Camelus dromedarius",
"炎",
"イタチ",
"ミンク",
"polecat、フィッチ、ファウルマート、ファウマート、Mustela putorius",
"黒足フェレット、フェレット、Mustela nigripes",
"カワウソ",
"スカンク、polecat、ウッドプッシー",
"狸",
"アルマジロ",
"ナマケモノナマケモノ、ai、Bradypus tridactylus",
"オランウータン、人々、債務者、Pongo pygmaeus",
"ゴリラ、ゴリラゴリラ",
"チンパンジー、チンパンジー、パン",
"テナガザル、Hylobates lar",
"サイエントロジー、Hylobates syndactylus、Symphalangus syndactylus",
"グエノン、グエノンモンキー",
"パトゥス、フセールマンケイ、エリトロス",
"ヒヒ",
"マカク",
"長いです",
"コロブス、コロブスモンキー",
"テントウムシ猿、Nasalis larvatus",
"マーモセット",
"カプチン、リングテール、Cebus capucinus",
"ハウラー猿、ハウラー",
"ティティ、ティティモンキー",
"クモザル、Ateles geoffroyi",
"リスザル、Saimiri sciureus",
"マダガスカル猫、オオキツネザル、キツネザルcatta",
"インドリ、インドリ、インドリインドリ、インドリbrevicaudatus",
"インドゾウ、Elephas maximus",
"アフリカゾウ、Loxodonta africana",
"小さいパンダ、レッサーパンダ、パンダ、クマの猫、猫のクマ、Ailurus fulgens",
"ジャイアントパンダ、パンダ、パンダベア、クーンベア、Ailuropoda melanoleuca",
"バラクータ、パイク",
"うなぎ",
"coho、cohoe、cohoサーモン、ブルージャック、シルバーサーモン、Oncorhynchus kisutch",
"岩の美しさ、Holocanthusトリコロール",
"アネモネフィッシュ",
"チョウザメ",
"gar、garfish、garpike、billfish、Lepisosteus osseus",
"ミノカサゴ",
"ふぐ、ふぐ、ふぐ、ふぐ",
"そろばん",
"アバヤ",
"アカデミックガウン、アカデミックローブ、裁判官のローブ",
"アコーディオン、ピアノアコーディオン、スクイズボックス",
"アコースティックギター",
"空母、キャリア、フラットトップ、攻撃空母",
"旅客機",
"飛行船、直行",
"祭壇",
"救急車",
"両生類、水陸両用車",
"アナログ時計",
"養蜂場、ミツバチの家",
"エプロン",
"ashcan、ゴミ箱、ゴミ箱、ゴミ箱、灰皿、灰皿、ashbin、ごみ箱、ゴミ箱、ゴミ箱",
"アサルトライフル、アサルトガン",
"バックパック、バックパック、ナップザック、パックサック、リュックサック、haversack",
"パン屋さん",
"バランスビーム、ビーム",
"バルーン",
"ボールペン、ボールペン、ボールペン、ビロ",
"バンドエイド",
"バンジョ",
"手すり、手すり、手すり、手すり子、手すり",
"バーベル",
"バーバーチェア",
"理髪店",
"子供",
"バロメーター",
"バレル、キャスク",
"手押し車、ガーデンカート、芝生カート、手押し車",
"野球",
"バスケットボール",
"バシネット",
"ファゴット",
"水泳帽、水泳帽",
"バスタオル",
"バスタブ、浴槽、バスタブ、浴槽",
"ビーチワゴン、ステーションワゴン、ワゴン、不動産車、ビーチワゴン、 ステーションワゴン、ワゴン",
"ビーコン、灯台、ビーコンライト、ファロス",
"ビーカー",
"ベアスキン、バスビー、しゃこ",
"ビール瓶",
"ビールグラス",
"ベルコート、ベルコット",
"よだれかけ",
"2人用自転車、タンデム自転車、タンデム",
"ビキニ、ツーピース",
"リングバインダー",
"双眼鏡、フィールドグラス、オペラグラス",
"巣箱",
"ボートハウス",
"ボブスレー、ボブスレー、ボブ",
"それはあなただった、それはあなただった",
"ボンネット、ポケボンネット",
"書棚",
"書店、書店、bookstall",
"瓶のキャップ",
"弓",
"蝶ネクタイ",
"真鍮製、記念式のタブレット、プラーク",
"ブラジャー、ブラジャー、ヘッドバンド",
"防波堤、鼠径部、防波堤、ほくろ、防波堤、防波堤、桟橋",
"胸当て、イージス、egis",
"ほうき",
"バケツ、バケツ",
"バックル",
"防弾チョッキ",
"新幹線、新幹線",
"肉屋、肉市場",
"タクシー、ハック、タクシー、タクシー",
"コールドロン、コールドロン",
"キャンドル、テーパー、ワックスライト",
"大砲",
"カヌー",
"缶切り、缶切り",
"カーディガン",
"車のミラー",
"カルーセル、カルーセル、メリーゴーランド、ロータリー、渦巻き",
"大工のキット、ツールキット",
"カートン",
"車のホイール",
"現金自動支払機、現金自動支払 機、自動預け払い機、自動預払機、自動預払機、自動預払機、ATM",
"カセット",
"カセット・プレーヤー",
"城",
"カタマラン",
"CDプレーヤー",
"チェロ、チェロ",
"携帯電話、携帯電話、携帯電話、携帯、携帯電話",
"鎖",
"チェーンリンクフェンス",
"チェーンメール、リングメール、メール、チェーンアーマー、チェーンアーマ ー、リングアーマー、リングアーマー",
"チェーンソー、チェーンソー",
"胸",
"シフォニア、チェスト",
"チャイム、ベル、ゴング",
"食器棚、食器棚",
"クリスマスの靴下",
"教会、教会の建物",
"映画館、映画館、映画館、映画館、絵画館",
"包丁、肉包丁、チョッパー",
"崖の住居",
"マント",
"下駄、下駄、パッテン、サボ",
"カクテルシェーカー",
"コーヒーマグカップ",
"コーヒーポット",
"コイル、スパイラル、渦巻、渦巻き、らせん",
"コンビネーションロック",
"コンピュータのキーボード、キーパッド",
"お菓子屋さん",
"コンテナ船、コンテナ船、コンテナ船",
"コンバーチブル",
"コルク抜き、ボトルねじ",
"コルネット、ホーン、トランペット、トランプ",
"カウボーイブーツ",
"カウボーイハット、10ガロンハット",
"ゆりかご",
"クレーン",
"クラッシュヘルメット",
"木枠",
"ベビーベッド、ベビーベッド",
"クロックポット",
"クロケットボール",
"松葉杖",
"キュイラス",
"価格、方向、側面",
"机",
"デスクトップコンピューター",
"ダイヤル電話、ダイヤル電話",
"おむつ、おむつ、ナプキン",
"デジタル時計",
"デジタル腕時計",
"ダイニングテーブル、ボード",
"ふきん、ふきん",
"食器洗い機、食器洗い機、食器洗い機",
"ディスクブレーキ、ディスクブレーキ",
"ドック、ドック、ドッキング施設",
"犬ぞり、そり、犬そり",
"ドメ",
"ドアマット、ウェルカムマット",
"掘削プラットフォーム、オフショアリグ",
"ドラム、メンブラノフォン、ティンパン",
"ドラムスティック",
"ダンベル",
"オランダのオーブン",
"扇風機、送風機",
"エレキギター",
"電気機関車",
"エンターテイメントセンター",
"エンベロープ",
"エスプレッソメーカー",
"フェースパウダー",
"良い羽毛製の襟巻",
"ファイル、ファイルキャビネット、ファイリングキャビネット",
"消防艇",
"消防車、消防車",
"防火スクリーン、消防署",
"フラッグポール、フラッグスタッフ",
"フルート、横フルート",
"折りたたみ椅子",
"フットボール用ヘルメット",
"フォークリフト",
"噴水",
"万年筆",
"四柱",
"貨車",
"フレンチホルン、ホーン",
"フライパン、フライパン、フライパン",
"毛皮のコート",
"ゴミ収集車",
"ガスマスク、マスク、ガスヘルメット",
"ガソリンポンプ、ガソリンポンプ、ガソリンポンプ、島ディスペンサー",
"ゴブレット",
"ゴーカート",
"ゴルフボール",
"ゴルフカート、ゴルフカート",
"ゴンドラ",
"ゴング、あそこに",
"ガウン",
"グランドピアノ",
"温室、保育園、グラスハウス",
"格子、ラジエ??ーター格子",
"食料品店、食料品、食品市場、マーケット",
"ギロチン",
"ヘアスライド",
"ヘアスプレー",
"ハーフトラック",
"ハンマー",
"妨げる",
"手の送風機、送風乾燥機、送風乾燥機、ヘアドライヤー、ヘアドライヤー",
"ハンドヘルドコンピュータ、ハンドヘルドマイクロコンピュータ",
"ハンカチ、ハンキー、ハンキー、ハンキー",
"ハードディスク、ハードディスク、固定ディスク",
"ハーモニカ、口オルガン、ハープ、マウスハープ",
"ハープ",
"収穫機、刈り取り機",
"手斧",
"ホルスター",
"ホームシアター、ホームシアター",
"ハニカム",
"フック、爪",
"フープスカート、クリノリン",
"水平バー、ハイバー",
"馬車、馬車",
"砂時計",
"iPod",
"アイロン、スムージングアイロン",
"鬼火",
"ジーンズ、ブルージーンズ、デニム",
"ジープ、ランドローバー",
"ジャージ、Tシャツ、Tシャツ",
"ジグソーパズル",
"Jinrickish、人力車、人力車",
"ジョイスティック",
"着物",
"膝パッド",
"結び目",
"白衣、白衣",
"とりべ",
"ランプシェード",
"ノートパソコン、ラップトップコンピュータ",
"芝刈り機",
"レンズキャップ、レンズカバー",
"レターオープナー、ペーパーナイフ、ペーパーナイフ",
"としょうかん",
"救命ボート",
"ライター、ライト、イグナイター、イグナイター",
"リムジン、リムジン",
"ライナー、オーシャンライナー",
"口紅、ルージュ",
"ローファー",
"ローション",
"スピーカー、スピーカー、スピーカーユニット、スピーカーシステム、スピーカーシステム",
"虫眼鏡宝石商の虫眼鏡",
"製材所、製材所",
"方位磁針",
"メールバッグ、ポストバッグ",
"メールボックス、レターボックス",
"シャツ",
"シャツ、タンクフォロー",
"マンホールの蓋",
"マラカ",
"マリンバ、木琴",
"マスク",
"マッチ棒",
"メイポール",
"迷路、迷路",
"計量カップ",
"薬箱、薬キャビネット",
"巨石、巨石の構造",
"マイク、マイク",
"電子レンジ、電子レンジ",
"軍服",
"ミルク缶",
"ミニバス",
"ミニスカート、ミニ",
"ミニバン",
"ミサイル",
"途中で",
"ミキシングボウル",
"モバイルホーム、製造ホーム",
"モデルT",
"モデム",
"修道院",
"モニター",
"モペット",
"モルタル",
"モルタルボード",
"モスク",
"蚊帳",
"モータースクーター、スクーター",
"マウンテンバイク、全地形対応自転車、オフローダー",
"山のテント",
"マウス、コンピューターのマウス",
"ネズミ捕り",
"移動バン",
"銃口",
"爪",
"ネックブレース",
"ネックレス",
"乳首",
"ノートパソコン、ノートパソコン",
"オベリスク",
"オーボエ、オーボーイ、オーボエ",
"オカリナ、さつまいも",
"走行距離計、走行距離計、走行距離計、ミリメーター",
"オイルフィルター",
"オルガン、パイプオルガン",
"オシロスコープ、スコープ、ブラウン管オシロスコープ、CRO",
"オーバースカート",
"牛車",
"酸素マスク",
"パケット",
"パドル、ボート用パドル",
"パドルホイール、パドルホイール",
"南京錠",
"絵筆",
"パジャマ、パジャマ、pjの、jammies",
"宮殿",
"パンパイプ、パンディーンパイプ、syrinx",
"ペーパータオル",
"パラシュート、秋",
"平行バー、バー",
"公園のベンチ",
"パーキングメーター",
"乗用車、コーチ、キャリッジ",
"パティオ、テラス",
"公衆電話、有料ステーション",
"台座、台座、フットスツール",
"筆箱、筆箱",
"鉛筆削り",
"香水、エッセンス",
"ペトリ皿",
"コピー機",
"バルブ、PLECTRONIAを選びます",
"Pickelhaube",
"ピケットフェンス、杭打ち",
"ピックアップ、ピックアップトラック",
"桟橋",
"貯金箱、ペニー銀行",
"錠剤瓶",
"枕",
"卓球ボール",
"風車",
"海賊、海賊船",
"ピッチャー、水差し",
"飛行機、大工の飛行機、木工飛行機",
"プラネタリウム",
"ビニール袋",
"プレートラック",
"すき、すき",
"プランジャー、配管工の助手",
"ポラロイドカメラ、ポラロイドランドカメラ",
"いいえ",
"警察バン、警察ワゴン、水田ワゴン、巡回ワゴン、ワゴン、黒マリア",
"ポンチョ",
"ビリヤード台、ビリヤード台、スヌーカー台",
"ポップボトル、ソーダボトル",
"ポット、植木鉢",
"ろくろ",
"電動ドリル",
"祈りの敷物、祈りのマット",
"プリンター",
"刑務所、刑務所の家",
"発射体、ミサイル",
"プロジェクター",
"パック、ホッケーパック",
"パンチングバッグ、パンチバッグ、パンチングボール、パンチボール",
"財布",
"羽ペン、羽ペン",
"キルト、掛け布団、快適さ、パフ",
"レーサー、レースカー、レーシングカー",
"ラケット、ラケット",
"ラジエーター",
"ラジオ、ワイヤレス",
"電波望遠鏡、電波リフレクター",
"レインバレル",
"レクリエーションビークル、RV、R.V.",
"リール",
"一眼レフカメラ",
"冷蔵庫、アイスボックス",
"リモコン、リモコン",
"レストラン、食べる家、食べる場所、飲食店",
"リボルバー、6ガン、6シューター",
"ライフル",
"ロッキングチェア、ロッカー",
"ロティサリー",
"消しゴム、消しゴム、消しゴム",
"ラグビーボール",
"支配、支配??者",
"ランニングシューズ",
"安全",
"安全ピン",
"ソルトシェーカー、ソルトシェーカー",
"サンダル",
"サロン",
"サックス、サックス",
"鞘",
"はかり、はかり",
"スクールバス",
"スクーナー",
"スコアボード",
"スクリーン、CRTスクリーン",
"スクリュー",
"ドライバー",
"シートベルト、シートベルト",
"ミシン",
"シールド、バックル",
"靴屋、靴屋、靴屋",
"所持",
"買い物カゴ",
"ショッピングカート",
"シャベル",
"シャワーキャップ",
"シャワーカーテン",
"スキー",
"目出し帽",
"寝袋",
"スライド規則、スリップスティック",
"引き戸",
"スロット、片腕強盗",
"スノーケル",
"スノーモービル",
"除雪機、除雪機",
"ソープディスペンサー",
"サッカーボール",
"靴下",
"ソーラーディッシュ、ソーラーコレクター、ソーラー炉",
"帽子",
"スープボウル",
"スペースキー",
"スペースヒーター",
"スペースシャトル",
"へら",
"スピードボート",
"クモの巣、クモの巣",
"スピンドル",
"スポーツカー、スポーツカー",
"スポットライト、スポット",
"ステージ",
"蒸気機関車",
"スチールアーチブリッジ",
"スチールドラム",
"聴診器",
"ストール",
"石垣",
"ストップウォッチ、ストップウォッチ",
"レンジ",
"ストレーナー",
"路面電車、路面電車、路面電車、トロリー、トロリー車",
"担架",
"スタジオソファー、デイベッド",
"ストゥーパ、トープ",
"潜水艦、ピッグボート、潜水艦、Uボート",
"スーツ、服のスーツ",
"日時計",
"サングラス",
"サングラス、サングラス、色合い",
"日焼け止め、日焼け止め、日焼け止め",
"つり橋",
"綿棒、綿棒、モップ",
"トレーナー",
"水泳パンツ、入浴パンツ",
"スイング",
"スイッチ、電気スイッチ、電気スイッチ",
"注射器",
"電気スタンド",
"タンク、軍タンク、装甲戦闘車、装甲戦闘車",
"テーププレイヤー",
"ティーポット",
"テディベア、テディベア",
"テレビ、テレビシステム",
"テニスボール",
"茅葺き屋根",
"シアターカーテン、シアターカーテン",
"指ぬき",
"脱穀機、脱穀機、脱穀機",
"王位",
"瓦屋根",
"トースター",
"たばこ屋、たばこ屋、たばこ屋",
"便座",
"トーチ",
"トーテムボックス",
"レッカー車、レッカー車、レッカー車",
"玩具屋",
"トラクター",
"トレーラートラック、トラクタートレーラー、トラック運搬用リグ、リグ、連結式トラック、セミ",
"トレイ",
"トレンチコート",
"三輪車、トライク、ヴェルシペード",
"トリマラン",
"三脚",
"凱旋門",
"トロリーバス、トロリーコーチ、無軌道トロリー",
"トロンボーン",
"浴槽、トーク",
"回転木戸",
"タイプライターキーボード",
"傘",
"一輪車、一輪車",
"アップライト、アップライトピアノ",
"掃除機、掃除機",
"花瓶",
"ボールト",
"ベルベット",
"自動販売機",
"ベスト",
"高架橋",
"バイオリン、フィドル",
"バレーボール",
"ワッフル焼き型",
"壁時計",
"財布、札入れ、ノートケース、手帳",
"ワードローブ、クローゼット、プレス",
"軍用機",
"洗面器、手洗い器、洗面器、ラバボ、洗面器",
"洗濯機、自動洗濯機、洗濯機",
"水筒",
"水差し",
"給水塔",
"ウイスキーの水差し",
"ホイッスル",
"かつら",
"ウインドウスクリーン",
"ブラインド",
"ウィンザーネクタイ",
"ワインボトル",
"翼",
"中華鍋",
"木製スプーン",
"ウール、ウール、ウール",
"ワームフェンス、ヘビフェンス、スネークレールフェンス、バージニアフェンス",
"大破",
"あくび",
"寮",
"ウェブサイト、ウェブサイト、インターネットサイト、サイト",
"コミックブック",
"クロスワードパズル、クロスワード",
"道路標識",
"信号機、信号機、ストップライト",
"ブックカバー、ダストカバー、ダストジャケット、ダストラッパー",
"メニュー",
"プレート",
"グアカモーレ",
"消費",
"鍋・鍋",
"ささいなこと",
"アイスクリーム、アイスクリーム",
"アイスキャンディー、キャンディー、ロリポップ、アイスキャンデー",
"フランスパン",
"ベーグル、ベーゲル",
"プレッツェル",
"チーズバーガー",
"ホットドッグ、ホットドッグ、レッドホット",
"マッシュポテト",
"ヘッドキャベツ",
"ブロッコリ",
"カリフラワー",
"ズッキーニ、ズッキーニ",
"スパゲッティスカッシュ",
"ドングリスカッシュ",
"バタースカッシュ",
"きゅうり",
"アーティチョーク、世界アーティチョーク",
"ピーマン",
"Cardoon",
"キノコ",
"グラニースミス",
"イチゴ",
"オレンジ",
"レモン",
"イチジク",
"パイナップル、アナナ",
"バナナ",
"ジャックフルーツ、ジャックのような",
"カスタードアップル",
"ザクロ",
"あります",
"カルボナーラ",
"チョコレートソース、チョコレートシロップ",
"生地",
"ミートローフ",
"ピザ、ピザパイ",
"potpie",
"ブリトー",
"赤ワイン",
"表現",
"カップ",
"エッグノッグ",
"アルプス",
"バブル",
"崖、ドロップ、ドロップオフ",
"サンゴ礁",
"間欠泉",
"湖畔、湖畔",
"岬、岬、頭、前地",
"サンドバー、サンドバー",
"海岸、海岸、海岸、海岸",
"バレー、バレ",
"火山",
"野球選手、野球選手",
"新郎新婦",
"スキューバダイバー",
"菜種",
"デイジー",
"黄色い女性のスリッパ、黄色い女性スリッパ、Cypripedium calceolus、Cypripedium parviflorum",
"コーン",
"どんぐり",
"ローズヒップローズヒップ",
"バックアイ、栗、トチの実",
"サンゴ菌",
"寒天",
"ジャイロミトラ",
"スティンホーン、腐肉菌",
"アーススター",
"森の中の鶏、森の中の鶏、Polyporus frondosus、Grifola frondosa",
"ボレテ",
"耳スパイク章",
"トイレットペーパー、トイレットペーパー、バスルームティッシュ",
}
